Repository mqbravo/compiladores_1, pull requests merged in 2019-10, with the labels that each got.

#12 Declaration
  .idea/misc.xml
  src/Core/Visitors/TableVisitor.java
  src/Core/Visitors/TreeVisitor.java
  src/Triangle/AbstractSyntaxTrees/LocalDeclaration.java
  src/Triangle/AbstractSyntaxTrees/RecursiveDeclaration.java
  src/Triangle/AbstractSyntaxTrees/VarDeclarationInitialized.java
  src/Triangle/AbstractSyntaxTrees/Visitor.java
  src/Triangle/CodeGenerator/Encoder.java
  src/Triangle/ContextualAnalyzer/Checker.java
  src/Triangle/SyntacticAnalyzer/Parser.java
  src/Triangle/TreeDrawer/LayoutVisitor.java
  test/Triangle/SyntacticAnalyzer/testProcFuncLocal.tri
  test/Triangle/SyntacticAnalyzer/testProcFuncRecursive.tri
  test/Triangle/SyntacticAnalyzer/testVarInit.tri
Labels: enhancement

#13 Xml writer
  .gitignore
  src/Core/Visitors/TreeVisitor.java
  src/Triangle/AbstractSyntaxTrees/AssignCommand.java
  src/Triangle/AbstractSyntaxTrees/VnameExpression.java
  src/Triangle/Compiler.java
  src/Triangle/IDECompiler.java
  src/Triangle/ProgramWriter/HTMLWriter.java
  src/Triangle/ProgramWriter/XMLWriter.java
  src/Triangle/ProgramWriter/XMLWriterVisitor.java
  src/Triangle/SyntacticAnalyzer/Scanner.java
  src/Triangle/SyntacticAnalyzer/SourceFile.java
Labels: enhancement

#18 Se elimina un archivo innecesario
  .idea/misc.xml
Labels: bug

#19 Separador de Carpetas del Sistema
  src/Triangle/IDECompiler.java
Labels: bugFix, enhancement

#20 Se agregan pruebas negativas y se comentan parseDeclaration y parseCo…
  src/Triangle/SyntacticAnalyzer/Parser.java
  test/Triangle/SyntacticAnalyzer/testForLoopError.tri
  test/Triangle/SyntacticAnalyzer/testFunc.tri
  test/Triangle/SyntacticAnalyzer/testFuncError.tri
  test/Triangle/SyntacticAnalyzer/testIfError.tri
  test/Triangle/SyntacticAnalyzer/testProc.tri
  test/Triangle/SyntacticAnalyzer/testProcError.tri
  test/Triangle/SyntacticAnalyzer/testProcFuncLocalError.tri
  test/Triangle/SyntacticAnalyzer/testProcFuncRecursiveError.tri
  test/Triangle/SyntacticAnalyzer/testProcFuncsError.tri
  test/Triangle/SyntacticAnalyzer/testUntilLoop2Error.tri
  test/Triangle/SyntacticAnalyzer/testUntilLoopError.tri
  test/Triangle/SyntacticAnalyzer/testVarInitError.tri
  test/Triangle/SyntacticAnalyzer/testWhileLoop2Error.tri
  test/Triangle/SyntacticAnalyzer/testWhileLoopError.tri
Labels: documentation

#21 Se crea el Jar del program. Se realiza una modificación para que se
  .gitignore
  .idea/artifacts/ide_triangle_v1_1_src_jar.xml
  dist/IDE-Triangle.jar
  source/META-INF/MANIFEST.MF
  src/Triangle/ProgramWriter/HTMLWriter.java
  src/Triangle/ProgramWriter/XMLWriter.java
Labels: enhancement

#22 Implementación de los Ciclos, y InitializedVariable
  src/Triangle/AbstractSyntaxTrees/VarDeclarationInitialized.java
  src/Triangle/ContextualAnalyzer/Checker.java
  src/Triangle/IDECompiler.java
  test/Triangle/ContextualAnalyzer/declaration.tri
  test/Triangle/SyntacticAnalyzer/testForLoop.tri
Labels: enhancement
