Repository mqbravo/compiladores_1, pull requests merged in 2019-11, with the labels that each got.

#29 Recursive declaration
  src/Core/Visitors/TreeVisitor.java
  src/GUI/Main.java
  src/Triangle/AbstractSyntaxTrees/Identifier.java
  src/Triangle/AbstractSyntaxTrees/RecursiveDeclaration.java
  src/Triangle/ContextualAnalyzer/Checker.java
  src/Triangle/ContextualAnalyzer/IdentificationTable.java
  src/Triangle/ContextualAnalyzer/PendingCall.java
  src/Triangle/ContextualAnalyzer/PendingCallCommand.java
  src/Triangle/ContextualAnalyzer/PendingCallExpression.java
  src/Triangle/ProgramWriter/XMLWriterVisitor.java
  src/Triangle/TreeDrawer/LayoutVisitor.java
  test/Triangle/ContextualAnalyzer/localDeclarationError.tri
  test/Triangle/ContextualAnalyzer/recursive.tri
  test/Triangle/ContextualAnalyzer/recursive_params.tri
  test/Triangle/ContextualAnalyzer/recursive_params_error.tri
  test/Triangle/ContextualAnalyzer/recursive_params_error_1.tri
  test/Triangle/ContextualAnalyzer/testConstDeclarationError.tri
  test/Triangle/ContextualAnalyzer/testForLoopVisibility.tri
  test/Triangle/ContextualAnalyzer/testFull.tri
  test/Triangle/ContextualAnalyzer/testLoopDeclarationReference.tri
  test/Triangle/ContextualAnalyzer/testLoopDeclarationReferenceError.tri
  test/Triangle/ContextualAnalyzer/testProc.tri
  test/Triangle/ContextualAnalyzer/testRecursive.tri
  test/Triangle/ContextualAnalyzer/testRecursiveError.tri
  test/Triangle/ContextualAnalyzer/testRecursiveForLoop.tri
  test/Triangle/ContextualAnalyzer/testRecursiveFuture.tri
  test/Triangle/ContextualAnalyzer/testRecursiveFutureFuncParameter.tri
  test/Triangle/ContextualAnalyzer/testRecursiveFutureProcParameter.tri
  test/Triangle/ContextualAnalyzer/testRecursiveFutureVarParameter.tri
  test/Triangle/ContextualAnalyzer/testRecursiveNestedFuture.tri
  test/Triangle/ContextualAnalyzer/testRecursivePast.tri
  test/Triangle/ContextualAnalyzer/testRecursiveWhileLoop.tri
  test/Triangle/ContextualAnalyzer/testVarDeclaration.tri
  test/Triangle/ContextualAnalyzer/unicidad_params_error.tri
Labels: enhancement

#31 Variables Locales Repetidas
  src/Triangle/ContextualAnalyzer/Checker.java
  src/Triangle/ContextualAnalyzer/IdentificationTable.java
  test/Triangle/ContextualAnalyzer/testD1EqualsD2LocalVariablesError.tri
  test/Triangle/ContextualAnalyzer/testDuplicatedLocalVariable.tri
  test/Triangle/ContextualAnalyzer/testDuplicatedLocalVariableError.tri
  test/Triangle/ContextualAnalyzer/testDuplicatedLocalVariablesError.tri
  test/Triangle/ContextualAnalyzer/testDuplicatedVariableError.tri
Labels: bugFix, risk

#32 Local Declaration
  .gitignore
  src/Core/Visitors/TableVisitor.java
  src/GUI/Main.java
  src/Triangle/CodeGenerator/Encoder.java
  src/Triangle/CodeGenerator/Frame.java
  src/Triangle/ContextualAnalyzer/Checker.java
  src/Triangle/IDECompiler.java
  test/Triangle/CodeGeneration/testCode.tri
  test/Triangle/CodeGeneration/testLocal.tri
  test/Triangle/ContextualAnalyzer/testNestedLocal.tri
Labels: enhancement

#39 Initialized Variable
  src/Core/Visitors/TableVisitor.java
  src/Triangle/CodeGenerator/Encoder.java
  src/Triangle/CodeGenerator/KnownAddressWithValue.java
  test/Triangle/CodeGeneration/testCharVariable.tri
  test/Triangle/CodeGeneration/testInitializedRecord.tri
  test/Triangle/CodeGeneration/testInitializedVariable.tri
Labels: enhancement

#38 D1==D2
  dist/IDE-Triangle.jar
  src/Triangle/ContextualAnalyzer/Checker.java
  src/Triangle/ContextualAnalyzer/IdentificationTable.java
  test/Triangle/ContextualAnalyzer/testD1EqualsD2LocalVariablesError.tri
Labels: risk

#43 Arreglos en analizador sintáctico
  dist/IDE-Triangle.jar
  src/Triangle/SyntacticAnalyzer/Parser.java
  test/Triangle/SyntacticAnalyzer/testMultipleLineProc.tri
  test/Triangle/SyntacticAnalyzer/testMultipleLineRecProc.tri
Labels: bugFix

#45 Fix de chequeo de tipo en llamada futura de param
  src/Triangle/ContextualAnalyzer/Checker.java
  src/Triangle/ContextualAnalyzer/FutureCallExpression.java
  test/Triangle/CodeGeneration/actual_param_future_call.tri
  test/Triangle/CodeGeneration/actual_param_future_call_with_typedef.tri
Labels: bugFix

#41 Cambios en la apariencia del editor de texto
  dist/IDE-Triangle.jar
  src/Core/Console/OutputRedirector.java
  src/Core/ExampleFileFilter.java
  src/GUI/FileFrame.form
  src/GUI/FileFrame.java
  src/GUI/Main.java
  src/Triangle/TreeDrawer/Drawer.java
Labels: enhancement

#50 Loop implementation
  src/Core/Visitors/TableVisitor.java
  src/Core/Visitors/TreeVisitor.java
  src/GUI/Main.java
  src/TAM/Interpreter.java
  src/Triangle/AbstractSyntaxTrees/ForLoopCommand.java
  src/Triangle/CodeGenerator/Encoder.java
  src/Triangle/ContextualAnalyzer/Checker.java
  src/Triangle/IDECompiler.java
  src/Triangle/ProgramWriter/XMLWriterVisitor.java
  src/Triangle/SyntacticAnalyzer/Parser.java
  src/Triangle/TreeDrawer/LayoutVisitor.java
  test/Triangle/CodeGeneration/ForLoopWithProc.tri
  test/Triangle/CodeGeneration/Loops_with_recursive_local/doUntilLoop_with_local_recursive.tri
  test/Triangle/CodeGeneration/Loops_with_recursive_local/doWhileLoop_with_local_recursive.tri
  test/Triangle/CodeGeneration/Loops_with_recursive_local/forLoop_with_local_recursive.tri
  test/Triangle/CodeGeneration/Loops_with_recursive_local/untilLoop_with_local_recursive.tri
  test/Triangle/CodeGeneration/Loops_with_recursive_local/whileLoop_with_local_recursive.tri
  test/Triangle/CodeGeneration/ProcForLoopTest.tri
  test/Triangle/CodeGeneration/doUntilLoopCommand.tri
  test/Triangle/CodeGeneration/doWhileLoopTest.tri
  test/Triangle/CodeGeneration/forLoopCommand.tri
  test/Triangle/CodeGeneration/forLoopCommandError.tri
  test/Triangle/CodeGeneration/letForLoopTest.tri
  test/Triangle/CodeGeneration/recursive_big.tri
  test/Triangle/CodeGeneration/simpleForLoop.tri
  test/Triangle/CodeGeneration/testForLoop.tri
  test/Triangle/CodeGeneration/untilLoopTest.tri
  test/Triangle/CodeGeneration/whileLoopCommand.tri
Labels: enhancement, risk

#51 Se agrega prueba de nested for loops
  dist/IDE-Triangle.jar
  src/Triangle/CodeGenerator/Encoder.java
  test/Triangle/CodeGeneration/nestedForLoopCommandTest.tri
Labels: enhancement
